# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'connection_pool'
gem 'loga'
gem 'pg'
gem 'sinatra', '~>2.0'
gem 'sinatra-contrib'

group :test do
  gem 'rspec'
  gem 'rack-test'
end
